sudo : required
services:
  - docker

before_install:
  - docker build -t preethamdivakar/docker-react -f Dockerfile.dev .
  - gem uninstall logger -aIx || true
  - gem install logger -v 1.7.0
  - gem install bundler

script:
  - docker run -e CI=true preethamdivakar/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-730335454937"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key: "$AWS_SECRET_KEY"
